name: build_khadas

on: push

jobs:
  install_cross-compiler:
    runs-on: self-hosted
    steps:
      - name: Install U-Boot cross-compiler
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd:
            wget https://releases.linaro.org/archive/13.11/components/toolchain/binaries/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux.tar.bz2
            wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
            sudo mkdir -p /opt/toolchains
            sudo tar -xjf gcc-linaro-aarch64-none-elf-4.8-2013.11_linux.tar.bz2 -C /opt/toolchains
            sudo tar -xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt/toolchains
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Install Linux kernel cross-compiler
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.02/arm-linux-gnueabihf/gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabihf.tar.xz
            wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.02/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu.tar.xz
            sudo mkdir -p /opt/toolchains
            sudo tar xvJf gcc-linaro-6.3.1-2017.02-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/toolchains
            sudo tar xvJf gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu.tar.xz -C /opt/toolchains
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Install git-lfs
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: mkdir -p $GITHUB_WORKSPACE/git_lfs
            cd $GITHUB_WORKSPACE/git_lfs
            wget https://github.com/git-lfs/git-lfs/releases/download/v2.3.4/git-lfs-linux-amd64-2.3.4.tar.gz
            tar xvzf git-lfs-linux-amd64-2.3.4.tar.gz
            cd git-lfs-2.3.4
            sudo ./install.sh
            git lfs install
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Download Source Code
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: mkdir -p $GITHUB_WORKSPACE/android
            cd $GITHUB_WORKSPACE/android
            repo init -u https://github.com/khadas/android_manifest.git -b khadas-vims-pie
            repo sync -j4 -c --no-clone-bundle
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Build U-Boot
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: cd $GITHUB_WORKSPACE/android
            cd bootloader/uboot
            ./mk kvim
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Build Android
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: cd $GITHUB_WORKSPACE/android
            source build/envsetup.sh
            lunch kvim-userdebug
            make -j4 otapackage
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Upload U-Boot artifacts
        uses: actions/upload-artifact@v2
        with:
          name: U-Boot
          path: |
            $GITHUB_WORKSPACE/android/bootloader/uboot/build/u-boot.bin
            $GITHUB_WORKSPACE/android/bootloader/uboot/build/u-boot.bin.sd.bin
      - name: Upload Android artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: $GITHUB_WORKSPACE/android/out/target/product/kvim/update.img
