name: build_khadas

on: push

jobs:
  install_cross-compiler:
    runs-on: self-hosted
    steps:
      - name: Download Source Code
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: mkdir -p $GITHUB_WORKSPACE/android &&
            cd $GITHUB_WORKSPACE/android &&
            repo init -u https://github.com/sousmangoosta/khadas_android_manifest.git -b khadas-vims-pie --depth=1 --partial-clone --clone-filter=blob:limit=10M &&
            repo sync -j$(nproc --all) -c --no-clone-bundle --no-tags -v
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Build U-Boot
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: cd $GITHUB_WORKSPACE/android &&
            cd bootloader/uboot &&
            ./mk kvim
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Build Android
        uses: sousmangoosta/android_build_docker_image@master
        with:
          cmd: echo -e "[user]\nname = ${{ secrets.gitusername }}\nemail = ${{ secrets.gitemail }}"
            > /home/android/.gitconfig &&
            PATH=$PATH:$GITHUB_WORKSPACE/android/bootloader/uboot/build/tools &&
            cd $GITHUB_WORKSPACE/android &&
            source build/envsetup.sh &&
            export BOARD_COMPILE_ATV=true &&
            lunch kvim-userdebug &&
            make -j$(nproc --all) otapackage
          gitusername: ${{ secrets.gitusername }}
          gitemail: ${{ secrets.gitemail }}
      - name: Upload U-Boot artifacts
        uses: actions/upload-artifact@v2
        with:
          name: U-Boot
          path: |
            android/bootloader/uboot/build/u-boot.bin
            android/bootloader/uboot/build/u-boot.bin.sd.bin
      - name: Upload Android artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android
          path: android/out/target/product/kvim/update.img
